# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

#config:
#  excludes: ['**/gen/**']

formatting:
  Indentation:
    continuationIndentSize: 4
  ParameterListWrapping:
    indentSize: 4
  MaximumLineLength:
    active: false

style:
  ReturnCount:
    active: false
  MaxLineLength:
    active: false
  MagicNumber:
    active: false